[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'vim-scripts/gtags.vim'
hook_add = '''
map <C-g> :Gtags
map <C-h> :Gtags -f %<CR>
map <C-j> :GtagsCursor<CR>
map <C-n> :cn<CR>
map <C-p> :cp<CR>
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = 'noremap <C-X><C-T> :VimFiler -split -simple -winwidth=45 -no-quit<ENTER>'
hook_source = 'let g:vimfiler_as_default_explorer = 1'

[[plugins]]
repo = 'elixir-editors/vim-elixir'
